version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://therapy_user:therapy_pass@db:5432/therapy_assistant
      - SECRET_KEY=your-super-secret-key-change-in-production
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - vector_data:/app/data/vector_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=therapy_assistant
      - POSTGRES_USER=therapy_user
      - POSTGRES_PASSWORD=therapy_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  vector_data: